version: "3.8"

services:
  # flask_app:
  #   build: .
  #   container_name: flask_app
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - milvus
  #     - mysql
  #     - redis
  #   environment:
  #     - FLASK_APP=run.py
  #     - FLASK_ENV=development
  #     - OPENAI_API_KEY=your-openai-api-key
  #     - MILVUS_DB_HOST=milvus
  #     - MILVUS_DB_PORT=19530
  #     - MYSQL_HOST=mysql
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=rootpassword
  #     - MYSQL_DATABASE=flaskdb
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: flask run --host=0.0.0.0 --port=5000

  # mysql:
  #   image: mysql:latest
  #   container_name: mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=rootpassword
  #     - MYSQL_DATABASE=flaskdb
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"

# volumes:
#   milvus_data:
#   mysql_data:
