version: '3.8'

services:
  # proofly-nginx:
  #   build: ./z-docker-resource/nginx/
  #   container_name: nginx-proofly
  #   ports:
  #     - 2380:80
  #   volumes:
  #     - ./z-docker-resource/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./plagiarism_checker_app:/var/www/laravel
  #   depends_on:
  #     - php-proofly
  #   networks:
  #     - proofly

  # proofly-php:
  #   build: ./z-docker-resources/php/
  #   container_name: php-proofly
  #   expose:
  #     - 9000
  #   volumes:
  #     - ./plagiarism_checker_app:/var/www/laravel
  #   networks:
  #     - proofly

  proofly-app:
    build:
      context: .
      dockerfile: ./plagiarism_checker_app/Dockerfile
    container_name: proofly-app
    volumes:
      - ./plagiarism_checker_app:/var/www/laravel
    environment:
      - APP_ENV=${APP_ENV:-local}
      - DB_HOST=proofly-mysql
      - DB_DATABASE=db_proofly
      - DB_USERNAME=${DB_USER:-proofly}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    depends_on:
      proofly-mysql:
        condition: service_healthy
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - proofly

  proofly-service:
    build:
      context: .
      dockerfile: ./plagiarism_checker_service/Dockerfile
    container_name: proofly-service
    volumes:
      - ./plagiarism_checker_service:/app
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - MILVUS_ALIAS=proofly
      - MILVUS_DB_NAME=db_proofly
      - MILVUS_DB_HOST=proofly-milvus-standalone
      - MILVUS_DB_PORT=19530
      - MILVUS_DB_USERNAME=${MILVUS_USERNAME:-root}
      - MILVUS_DB_PASSWORD=${MILVUS_PASSWORD:-password}
    depends_on:
      proofly-milvus-standalone:
        condition: service_healthy
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/v1/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - proofly

  proofly-mysql:
    container_name: proofly-mysql
    restart: always
    image: mysql:8.0
    ports:
      - 3306:3306
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: db_proofly
      MYSQL_USER: ${DB_USER:-proofly}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - ./z-docker-resources/volumes/mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - proofly

  proofly-phpmyadmin:
    container_name: proofly-phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=proofly-mysql
      - MYSQL_ROOT_PASSWORD=password
      - PMA_USER=proofly
      - PMA_PASSWORD=password
    ports:
      - 8383:80
    depends_on:
      - proofly-mysql
    networks:
      - proofly

  proofly-attu:
    image: zilliz/attu:v2.5.6
    container_name: proofly-attu
    ports:
      - "3000:3000"
    environment:
      - MILVUS_URL=http://proofly-milvus-standalone:19530
    depends_on:
      proofly-milvus-standalone:
        condition: service_healthy
    networks:
      - proofly

  proofly-milvus-etcd:
    container_name: proofly-milvus-etcd
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./z-docker-resources/volumes/etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - proofly

  proofly-milvus-minio:
    container_name: proofly-milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - ./z-docker-resources/volumes/minio_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - proofly

  proofly-milvus-standalone:
    container_name: proofly-milvus-standalone
    image: milvusdb/milvus:v2.5.6
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: proofly-milvus-etcd:2379
      MINIO_ADDRESS: proofly-milvus-minio:9000
      MILVUS_ENABLE_AUTH: ${MILVUS_ENABLE_AUTH:-true}
      MILVUS_USER: ${MILVUS_USERNAME:-root}
      MILVUS_PASSWORD: ${MILVUS_PASSWORD:-password}
    volumes:
      - ./z-docker-resources/volumes/milvus_data:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "${MILVUS_PORT:-19530}:19530"
      - "${MILVUS_METRICS_PORT:-9091}:9091"
    depends_on:
      proofly-milvus-etcd:
        condition: service_healthy
      proofly-milvus-minio:
        condition: service_healthy
    networks:
      - proofly

volumes:
  mysql_data:
  etcd_data:
  minio_data:
  milvus_data:

networks:
  proofly:
    driver: bridge
    name: proofly